version: '3.3'

services:
   mariaDBLocalhost:
     image: mariadb:latest
     restart: always
     ports:
       - "3306:3306"
     volumes:
        - dbvolume:/var/lib/mysql    
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: 
       MYSQL_USER: admin
       MYSQL_PASSWORD: admin
     command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --wait_timeout=2000
volumes:
  dbvolume:    
