version: '3.3'

services:
   mariaDBLocalhost:
     image: mariadb:latest
     restart: always
     ports:
       - "3306:3306"
     volumes:
        - dbvolume:/var/lib/mysql    
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: university
       MYSQL_USER: admin
       MYSQL_PASSWORD: admin
     command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --wait_timeout=2000

   uni-spring:
     depends_on:
       - mariaDBLocalhost
     image: uni-spring:latest
     build:
       context: .
       dockerfile: ./Dockerfile
     ports:
       - "8080:8080"
     environment:
       DB_HOST: mariaDBLocalhost
       DB_PORT: 3306
       MYSQL_USER: root
       MYSQL_PASSWORD: root

volumes:
  dbvolume:    
